// ReLoop AI — Listing model (a listing can be any resource category, not just food)
const mongoose = require('mongoose');

const CATEGORIES = ['food', 'electronics', 'furniture', 'books', 'clothes', 'medical', 'recyclables'];
const STATUSES   = ['pending', 'ai_processing', 'ai_ready', 'notified', 'accepted', 'assigned', 'in_transit', 'delivered', 'expired', 'cancelled'];
const PRIORITIES = ['low', 'normal', 'high', 'critical'];

const listingSchema = new mongoose.Schema({
  // Auto-generated by LLM from the AI analysis (donor no longer types these)
  title:       { type: String, default: 'Untitled listing' },
  description: { type: String, default: '' },
  category:    { type: String, enum: CATEGORIES, required: true, default: 'food' },

  // Vision AI + OCR outputs
  ai: {
    itemDetected:      { type: String },
    condition:         { type: String, enum: ['fresh', 'sealed', 'used_good', 'used_fair', 'damaged', 'unknown'], default: 'unknown' },
    quantityEstimate:  { type: Number },
    quantityUnit:      { type: String, default: 'unit' },   // kg, unit, box, etc.
    ocrText:           { type: String },
    detectedExpiry:    { type: Date },
    productName:       { type: String },
    llmModel:          { type: String },
    visionModel:       { type: String },
    confidence:        { type: Number, default: 0 },
    generatedAt:       { type: Date },
  },

  // Locations
  pickupLocation:   { type: String, required: true },
  pickupCoords:     { lat: Number, lng: Number },

  // Legacy compatibility (kept so old routes keep working)
  foodType:         { type: String },
  quantity:         { type: Number },
  expirationDate:   { type: Date },
  imageUrl:         { type: String },

  priority:         { type: String, enum: PRIORITIES, default: 'normal' },
  status:           { type: String, enum: STATUSES, default: 'pending' },

  donor:            { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  receiver:         { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  volunteer:        { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

  // AI matching — ranked list of recipient candidates
  matches: [{
    recipient:      { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    score:          Number,          // 0..100
    distanceKm:     Number,
    urgencyScore:   Number,
    storageScore:   Number,
    categoryMatch:  Number,
    availabilityScore: Number,
    reason:         String,
  }],

  // Automation state (n8n workflow references)
  automation: {
    workflowId:     String,          // e.g. 'wf-01-donation-lifecycle'
    executionId:    String,
    lastStep:       String,
    notifiedAt:     Date,
    approvedAt:     Date,
    assignedAt:     Date,
    pickedUpAt:     Date,
    deliveredAt:    Date,
  },

  // Impact report generated by LLM after pickup
  impact: {
    mealsSaved:     Number,
    co2SavedKg:     Number,
    wasteDivertedKg:Number,
    summary:        String,
    certificateUrl: String,          // PDF certificate URL
    generatedAt:    Date,
  },

  otp:        { type: String, default: null },
  otpExpires: { type: Date,   default: null },

  createdAt:  { type: Date, default: Date.now },
  updatedAt:  { type: Date, default: Date.now },
});

listingSchema.pre('save', function (next) {
  this.updatedAt = new Date();
  next();
});

listingSchema.statics.CATEGORIES = CATEGORIES;
listingSchema.statics.STATUSES = STATUSES;
listingSchema.statics.PRIORITIES = PRIORITIES;

// Registered under the original name so existing controllers keep working.
module.exports = mongoose.model('Donation', listingSchema);
